### PR TITLE
Navigation Reorg

### PR DESCRIPTION
**Pull request by TelegramSam**
All content is still present, but has been reorganized to take advantage of top level navigation. Some stub pages were added.

### CODE REVIEW

**Comment by TelegramSam** [comment]
This is hard to visualize without running mkdocs for review. I'd be happy to jump on a screen share to show before and after. Just ping me on Discord.

**Comment by TelegramSam** [comment]
Discussed UG 20230918. No opposition to a merge.

**Comment by swcurran** [comment]
Looks pretty good.  I would add instructions on how to get it running locally. I’ve used mkdocs before, so easy enough.

FYI: I just use this to run it from the root of the repo.

`docker run --rm -it -p 8000:8000 --name mkdocs-material -v ${PWD}:/docs squidfunk/mkdocs-material`

**Review by rodolfomiranda — APPROVED** [review]
LGTM

**Pull request merged**
